export const GET_ALL_LAUNCHES_INIT = "GET_ALL_LAUNCHES_INIT";
export const GET_ALL_LAUNCHES = "GET_ALL_LAUNCHES";
export const GET_ALL_SUCCESS_LAUNCHES = "GET_ALL_SUCCESS_LAUNCHES";
export const GET_ALL_SUCCESS_LAUNCHES_LANDED =
  "GET_ALL_SUCCESS_LAUNCHES_LANDED";
export const GET_ALL_LAUNCHES_BY_YEAR = "GET_ALL_LAUNCHES_BY_YEAR";

export const LAUNCH_ERROR = "LAUNCH_ERROR";
